services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: homework3_db
    networks: 
      - homework3-network
  app:
    image: big_data_hw3_image:1.0
    depends_on:
      - database
    networks:
      - homework3-network

networks:
  homework3-network:
    driver: bridge



